---
kind: pipeline
type: docker
name: 2_Steps_Build

steps:

- name: 1_PreCheck_scripts
  image: alpine
  commands:
  - echo Checking if I am anonymous or any operations
  - cat /etc/*-release
  - whoami

- name: 2_Build_The_Code
  image: alpine
  commands:
  - echo A Build Simulation
  - echo DONE
